name: elastic_dart
version: 0.2.1
description: An Elasticsearch connector for Dart
homepage: https://github.com/Pajn/ElasticDart
authors:
- Jesper HÃ¥kansson <jesper@jesperh.se>
- Rasmus Eneman <rasmus@eneman.eu>
dependencies:
  http: '>=0.11.1+3 <0.12.0'
  warehouse: ">=0.1.0 <0.2.0"
dev_dependencies:
  guinness: '>=0.1.17 <0.2.0'
  unittest: '>=0.11.0 <0.12.0'
